module Czech exposing (words)


words : List ( String, Float )
words =
    [ ( "asran", 0.2 )
    , ( "blb", 0.2 )
    , ( "buzn", 0.2 )
    , ( "buzer", 0.2 )
    , ( "čubk", 0.2 )
    , ( "čurák", 0.2 )
    , ( "debil", 0.2 )
    , ( "demen", 0.2 )
    , ( "děvk", 0.2 )
    , ( "dylin", 0.2 )
    , ( "feťák", 0.2 )
    , ( "hajzl", 0.2 )
    , ( "hovad", 0.2 )
    , ( "hovn", 0.2 )
    , ( "chcan", 0.2 )
    , ( "chcat", 0.2 )
    , ( "chčij", 0.2 )
    , ( "čurák", 0.2 )
    , ( "idiot", 0.2 )
    , ( "jeb", 0.2 )
    , ( "kedr", 0.2 )
    , ( "kokot", 0.2 )
    , ( "koz", 0.2 )
    , ( "kráv", 0.2 )
    , ( "kretén", 0.2 )
    , ( "kripl", 0.2 )
    , ( "ksicht", 0.2 )
    , ( "kund", 0.2 )
    , ( "kurv", 0.2 )
    , ( "kuřbuřt", 0.2 )
    , ( "mrd", 0.2 )
    , ( "osel", 0.2 )
    , ( "píč", 0.2 )
    , ( "pipin", 0.2 )
    , ( "poděla", 0.2 )
    , ( "poser", 0.2 )
    , ( "pošuk", 0.2 )
    , ( "prd", 0.2 )
    , ( "prsatic", 0.2 )
    , ( "smažk", 0.2 )
    , ( "ser", 0.2 )
    , ( "srač", 0.2 )
    , ( "srát", 0.2 )
    , ( "šoust", 0.2 )
    , ( "šuk", 0.2 )
    , ( "úchyl", 0.2 )
    , ( "úřední", 0.2 )
    , ( "úřad", 0.2 )
    , ( "vůl", 0.2 )
    , ( "vol", 0.2 )
    , ( "zmrd", 0.2 )
    , ( "zoofil", 0.2 )
    ]
